// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCV2Rqnsx__RloJ8WsGEG35tF6gsiHgAKc',
    appId: '1:552281624057:web:64a139703170792ad68128',
    messagingSenderId: '552281624057',
    projectId: 'whatsappclone-a61dc',
    authDomain: 'whatsappclone-a61dc.firebaseapp.com',
    storageBucket: 'whatsappclone-a61dc.appspot.com',
    measurementId: 'G-L9Z5615GJR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDK-BL8Rk_FXguD4gzrNlMKq5qdpUU3tQY',
    appId: '1:552281624057:android:324e5be7ea74cd77d68128',
    messagingSenderId: '552281624057',
    projectId: 'whatsappclone-a61dc',
    storageBucket: 'whatsappclone-a61dc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyByPQTb_DI5NUEdoURqj_glUlUufcG8K1k',
    appId: '1:552281624057:ios:cdea91faf518f8b3d68128',
    messagingSenderId: '552281624057',
    projectId: 'whatsappclone-a61dc',
    storageBucket: 'whatsappclone-a61dc.appspot.com',
    iosClientId: '552281624057-onp7ki2qjsgnbr7tftl6h8k5d0j5j369.apps.googleusercontent.com',
    iosBundleId: 'com.example.appWhatsapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyByPQTb_DI5NUEdoURqj_glUlUufcG8K1k',
    appId: '1:552281624057:ios:cdea91faf518f8b3d68128',
    messagingSenderId: '552281624057',
    projectId: 'whatsappclone-a61dc',
    storageBucket: 'whatsappclone-a61dc.appspot.com',
    iosClientId: '552281624057-onp7ki2qjsgnbr7tftl6h8k5d0j5j369.apps.googleusercontent.com',
    iosBundleId: 'com.example.appWhatsapp',
  );
}
